"""BPMN 2.0 XML Standard Exporter and Importer (Camunda & Zeebe Parity).

Converts live agent-saga execution histories to standard BPMN 2.0 XML diagrams,
and parses existing BPMN 2.0 XML workflow definitions into agent-saga execution plans.
"""

from __future__ import annotations

import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from typing import Any, Optional


@dataclass
class BPMNNode:
    id: str
    name: str
    node_type: str  # serviceTask, userTask, boundaryEvent, startEvent, endEvent
    compensation_for: Optional[str] = None


class BPMNExporter:
    """Exports agent-saga WAL records or execution graphs to BPMN 2.0 XML."""

    @classmethod
    def to_bpmn_xml(cls, records: list[dict[str, Any]], process_id: str = "AgentSagaProcess") -> str:
        root = ET.Element("bpmn:definitions", {
            "xmlns:bpmn": "http://www.omg.org/spec/BPMN/20100524/MODEL",
            "xmlns:bpmndi": "http://www.omg.org/spec/BPMN/20100524/DI",
            "xmlns:dc": "http://www.omg.org/spec/DD/20100524/DC",
            "targetNamespace": "http://bpmn.io/schema/bpmn",
        })
        process = ET.SubElement(root, "bpmn:process", {"id": process_id, "isExecutable": "true"})

        start = ET.SubElement(process, "bpmn:startEvent", {"id": "StartEvent_1", "name": "Start Saga"})

        seq = 0
        for r in records:
            event = r.get("event")
            if event == "STEP_COMMITTED":
                seq += 1
                tool = r.get("tool", f"step_{seq}")
                task_id = f"Task_{tool.replace('.', '_')}_{seq}"
                ET.SubElement(process, "bpmn:serviceTask", {"id": task_id, "name": f"Tool: {tool}"})

                if r.get("compensation"):
                    bound_id = f"BoundaryComp_{seq}"
                    comp_task_id = f"CompTask_{tool.replace('.', '_')}_{seq}"
                    ET.SubElement(process, "bpmn:boundaryEvent", {
                        "id": bound_id,
                        "attachedToRef": task_id,
                        "name": "Compensate",
                    })
                    ET.SubElement(process, "bpmn:serviceTask", {
                        "id": comp_task_id,
                        "name": f"Undo: {tool}",
                        "isForCompensation": "true",
                    })

        end = ET.SubElement(process, "bpmn:endEvent", {"id": "EndEvent_1", "name": "Saga Complete"})
        return ET.tostring(root, encoding="utf-8").decode("utf-8")


class BPMNImporter:
    """Parses standard BPMN 2.0 XML diagrams into agent-saga step nodes."""

    @classmethod
    def from_bpmn_xml(cls, xml_content: str) -> list[BPMNNode]:
        nodes = []
        try:
            root = ET.fromstring(xml_content)
            for elem in root.iter():
                tag = elem.tag.split("}")[-1] if "}" in elem.tag else elem.tag
                if tag in ("serviceTask", "userTask", "startEvent", "endEvent", "boundaryEvent"):
                    node_id = elem.attrib.get("id", "")
                    name = elem.attrib.get("name", node_id)
                    nodes.append(BPMNNode(id=node_id, name=name, node_type=tag))
        except Exception as exc:
            raise ValueError(f"Failed to parse BPMN XML: {exc}") from exc
        return nodes


_VALID_SEMANTICS = {"REVERSIBLE", "COMPENSABLE", "IRREVERSIBLE"}


def _ident(name: str) -> str:
    """A safe Python identifier fragment from a tool/saga name."""
    import re
    ident = re.sub(r"[^0-9a-zA-Z_]", "_", str(name)).strip("_")
    return ident or "step"


def generate_saga_code(steps: list[dict], *, name: str = "designed_saga") -> str:
    """Generate runnable ``saga_scope`` Python from a designed step list.

    Each step is ``{"tool": str, "semantics": "REVERSIBLE|COMPENSABLE|
    IRREVERSIBLE", "compensate": {"handler": str, "kwargs": {...}} | None}``.
    COMPENSABLE steps emit a ``compensate`` factory (a stub the developer fills
    in); REVERSIBLE/IRREVERSIBLE steps omit it, matching the engine's contract.
    The output is a real, importable module skeleton -- the forward bodies are
    TODOs, the structure and safety semantics are correct."""
    fn_name = f"run_{_ident(name)}"
    lines = [
        '"""Generated by agent-saga BPMN Studio. Fill in the forward actions."""',
        "",
        "from agent_saga import saga_scope, ActionSemantics",
        "from agent_saga.context import Compensation",
        "",
        "",
        f"async def {fn_name}():",
        f'    async with saga_scope(name="{name}") as ctx:',
    ]
    if not steps:
        lines.append("        pass  # no steps designed yet")
    for i, step in enumerate(steps, 1):
        tool = step.get("tool") or f"step_{i}"
        semantics = (step.get("semantics") or "IRREVERSIBLE").upper()
        if semantics not in _VALID_SEMANTICS:
            semantics = "IRREVERSIBLE"
        comp = step.get("compensate") if semantics == "COMPENSABLE" else None
        lines.append("")
        lines.append(f"        # Step {i}: {tool} ({semantics})")
        lines.append("        await ctx.execute(")
        lines.append(f'            tool="{tool}",')
        lines.append(f"            semantics=ActionSemantics.{semantics},")
        lines.append(f"            forward=lambda: ...,  # TODO: implement the {tool} call")
        if comp:
            handler = comp.get("handler") or f"{_ident(tool)}_undo"
            kwargs = comp.get("kwargs") or {}
            kwargs_src = ", ".join(f'"{k}": {_py_literal(v)}' for k, v in kwargs.items())
            lines.append("            compensate=lambda result: Compensation(")
            lines.append(f"                fn=...,  # TODO: implement {handler}")
            lines.append(f'                handler="{handler}",')
            lines.append(f"                kwargs={{{kwargs_src}}},")
            lines.append(f'                description="undo {tool}"),')
        lines.append("        )")
    lines.append("")
    return "\n".join(lines)


def _py_literal(value: Any) -> str:
    if isinstance(value, str):
        return repr(value)
    if isinstance(value, (int, float, bool)) or value is None:
        return repr(value)
    return repr(value)


def steps_to_records(steps: list[dict]) -> list[dict]:
    """Turn a designed step list into synthetic STEP_COMMITTED records so the
    existing BPMNExporter can render it as a diagram."""
    records = []
    for i, step in enumerate(steps, 1):
        rec = {"event": "STEP_COMMITTED", "tool": step.get("tool", f"step_{i}"),
               "step_id": f"st{i}"}
        semantics = (step.get("semantics") or "").upper()
        if semantics == "COMPENSABLE" or step.get("compensate"):
            comp = step.get("compensate") or {}
            rec["compensation"] = {"handler": comp.get("handler", f"undo_{i}")}
        records.append(rec)
    return records


def design_to_bpmn_xml(steps: list[dict], process_id: str = "DesignedSaga") -> str:
    """Render a designed step list as BPMN 2.0 XML via the exporter."""
    return BPMNExporter.to_bpmn_xml(steps_to_records(steps), process_id=process_id)


def saga_code_from_bpmn(xml_content: str, *, name: str = "imported_saga") -> str:
    """Import a BPMN diagram and generate saga_scope code from it. A serviceTask
    named ``Undo: X`` (or flagged for compensation) is treated as the
    compensation for step ``X``; steps with a compensation become COMPENSABLE,
    the rest default to the safe IRREVERSIBLE."""
    nodes = BPMNImporter.from_bpmn_xml(xml_content)
    undos = set()
    for n in nodes:
        if n.node_type == "serviceTask" and n.name.lower().startswith("undo:"):
            undos.add(n.name.split(":", 1)[1].strip())

    steps = []
    for n in nodes:
        if n.node_type != "serviceTask":
            continue
        label = n.name
        if label.lower().startswith("undo:"):
            continue
        tool = label.split(":", 1)[1].strip() if ":" in label else label
        has_comp = tool in undos
        steps.append({
            "tool": tool,
            "semantics": "COMPENSABLE" if has_comp else "IRREVERSIBLE",
            "compensate": {"handler": f"{_ident(tool)}_undo", "kwargs": {}} if has_comp else None,
        })
    return generate_saga_code(steps, name=name)


__all__ = [
    "BPMNNode", "BPMNExporter", "BPMNImporter",
    "generate_saga_code", "saga_code_from_bpmn", "design_to_bpmn_xml",
    "steps_to_records",
]
