"""`agent_saga/compiler_v2.py` -- Supreme Full-Stack Web & Mobile Engine Compiler.

Compiles any Python module, @saga decorators, and Pydantic models into a complete,
unseen.co-style Next.js 15 + Three.js 3D WebGL + Tailwind + Web Audio Haptics application.

Published & Maintained by: SAGAOPS Enterprise
Founder & Owner: Thomas J George (thomasjgeorge23@gmail.com)
"""

from __future__ import annotations

import json
from typing import Any, Callable, Dict, List, Optional
from agent_saga.ui_compiler import DeclarativeUISchema, compile_saga_ui


class SupremeFullStackCompiler:
    """Compiles Python saga workflows into a complete full-stack web application bundle."""

    def __init__(self, project_name: str = "supreme_saga_app"):
        self.project_name = project_name
        self.schemas: List[DeclarativeUISchema] = []

    def add_workflow(self, func: Callable[..., Any], title: Optional[str] = None) -> SupremeFullStackCompiler:
        schema = compile_saga_ui(func, title=title)
        self.schemas.append(schema)
        return self

    def generate_nextjs_page_component(self) -> str:
        """Generate Next.js 15 React page component source code."""
        return f"""// Generated by agent-saga v0.7.0 Supreme Full-Stack Compiler
import React from 'react';
import {{ UnseenSagaShowcase }} from '@/components/UnseenSagaShowcase';

export default function GeneratedSagaPage() {{
  return (
    <main className="min-h-screen bg-slate-950 text-white font-sans">
      <UnseenSagaShowcase />
    </main>
  );
}}
"""


__all__ = ["SupremeFullStackCompiler"]
