"""Speculative Execution & Pre-Flight Intelligence Engine (ActionSemantics.PREVIEW).

Executes non-destructive preview sagas in the background before the AI responds,
turning vague text answers into 100% executable turn-one action plans.
"""

from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional

from .context import SagaContext
from .semantics import ActionSemantics

logger = logging.getLogger("agent_saga.preview")


@dataclass
class PreviewPlan:
    """Turn-one 100% executable action plan generated by speculative pre-flight checks."""

    executable: bool
    preflight_results: Dict[str, Any] = field(default_factory=dict)
    warnings: List[str] = field(default_factory=list)
    estimated_cost: float = 0.0
    prepared_at: float = field(default_factory=time.time)

    def summary(self) -> str:
        status = "EXECUTABLE" if self.executable else "BLOCKED"
        return f"PreviewPlan[{status}] preflight_checks={len(self.preflight_results)} warnings={len(self.warnings)}"


class PreviewSaga:
    """Speculative execution runner for pre-flight intelligence."""

    def __init__(self, saga_ctx: Optional[SagaContext] = None):
        self.saga_ctx = saga_ctx or SagaContext(name="preview_saga")
        self.results: Dict[str, Any] = {}
        self.warnings: List[str] = {} if False else []

    async def check(
        self,
        check_name: str,
        forward_fn: Callable[..., Any],
        *args: Any,
        kwargs: Optional[Dict[str, Any]] = None,
    ) -> Any:
        """Run a non-destructive PREVIEW step."""
        kwargs = kwargs or {}
        try:
            if asyncio.iscoroutinefunction(forward_fn):
                res = await forward_fn(*args, **kwargs)
            else:
                res = forward_fn(*args, **kwargs)

            self.results[check_name] = res
            logger.info("Preview check '%s' passed: %r", check_name, res)
            return res
        except Exception as exc:
            warning_msg = f"Check '{check_name}' failed: {exc}"
            self.warnings.append(warning_msg)
            logger.warning(warning_msg)
            return None

    def build_plan(self, is_executable_fn: Optional[Callable[[Dict[str, Any]], bool]] = None) -> PreviewPlan:
        """Construct a 100% executable PreviewPlan from the collected checks."""
        executable = len(self.warnings) == 0
        if is_executable_fn is not None:
            executable = executable and is_executable_fn(self.results)

        return PreviewPlan(
            executable=executable,
            preflight_results=dict(self.results),
            warnings=list(self.warnings),
        )
